//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 12:14:39 PM CEST 
//


package it.cnr.isti.labsedc.bpmls.learningpathspec;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Prerequesties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PreLearningPath" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="pre_lpid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Competencies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Competency" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LearningActivities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LearningActivity" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="competencyid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LearningGoals">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LearningGoal" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LearningScenario">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="lsid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="KPIs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="competencyid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="processid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prerequesties",
    "competencies",
    "learningActivities",
    "learningGoals"
})
@XmlRootElement(name = "LearningPath")
public class LearningPath {

    @XmlElement(name = "Prerequesties", required = true)
    protected LearningPath.Prerequesties prerequesties;
    @XmlElement(name = "Competencies", required = true)
    protected LearningPath.Competencies competencies;
    @XmlElement(name = "LearningActivities", required = true)
    protected LearningPath.LearningActivities learningActivities;
    @XmlElement(name = "LearningGoals", required = true)
    protected LearningPath.LearningGoals learningGoals;
    @XmlAttribute(name = "competencyid")
    protected String competencyid;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "processid")
    protected String processid;

    /**
     * Gets the value of the prerequesties property.
     * 
     * @return
     *     possible object is
     *     {@link LearningPath.Prerequesties }
     *     
     */
    public LearningPath.Prerequesties getPrerequesties() {
        return prerequesties;
    }

    /**
     * Sets the value of the prerequesties property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningPath.Prerequesties }
     *     
     */
    public void setPrerequesties(LearningPath.Prerequesties value) {
        this.prerequesties = value;
    }

    /**
     * Gets the value of the competencies property.
     * 
     * @return
     *     possible object is
     *     {@link LearningPath.Competencies }
     *     
     */
    public LearningPath.Competencies getCompetencies() {
        return competencies;
    }

    /**
     * Sets the value of the competencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningPath.Competencies }
     *     
     */
    public void setCompetencies(LearningPath.Competencies value) {
        this.competencies = value;
    }

    /**
     * Gets the value of the learningActivities property.
     * 
     * @return
     *     possible object is
     *     {@link LearningPath.LearningActivities }
     *     
     */
    public LearningPath.LearningActivities getLearningActivities() {
        return learningActivities;
    }

    /**
     * Sets the value of the learningActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningPath.LearningActivities }
     *     
     */
    public void setLearningActivities(LearningPath.LearningActivities value) {
        this.learningActivities = value;
    }

    /**
     * Gets the value of the learningGoals property.
     * 
     * @return
     *     possible object is
     *     {@link LearningPath.LearningGoals }
     *     
     */
    public LearningPath.LearningGoals getLearningGoals() {
        return learningGoals;
    }

    /**
     * Sets the value of the learningGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningPath.LearningGoals }
     *     
     */
    public void setLearningGoals(LearningPath.LearningGoals value) {
        this.learningGoals = value;
    }

    /**
     * Gets the value of the competencyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompetencyid() {
        return competencyid;
    }

    /**
     * Sets the value of the competencyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompetencyid(String value) {
        this.competencyid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the processid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * Sets the value of the processid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessid(String value) {
        this.processid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Competency" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "competency"
    })
    public static class Competencies {

        @XmlElement(name = "Competency")
        protected List<LearningPath.Competencies.Competency> competency;

        /**
         * Gets the value of the competency property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the competency property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompetency().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LearningPath.Competencies.Competency }
         * 
         * 
         */
        public List<LearningPath.Competencies.Competency> getCompetency() {
            if (competency == null) {
                competency = new ArrayList<LearningPath.Competencies.Competency>();
            }
            return this.competency;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Competency {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "url")
            protected String url;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LearningActivity" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="competencyid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "learningActivity"
    })
    public static class LearningActivities {

        @XmlElement(name = "LearningActivity")
        protected List<LearningPath.LearningActivities.LearningActivity> learningActivity;

        /**
         * Gets the value of the learningActivity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the learningActivity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLearningActivity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LearningPath.LearningActivities.LearningActivity }
         * 
         * 
         */
        public List<LearningPath.LearningActivities.LearningActivity> getLearningActivity() {
            if (learningActivity == null) {
                learningActivity = new ArrayList<LearningPath.LearningActivities.LearningActivity>();
            }
            return this.learningActivity;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="competencyid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class LearningActivity {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "bpmn_activityid")
            protected String bpmnActivityid;
            @XmlAttribute(name = "competencyid")
            protected String competencyid;
            @XmlAttribute(name = "bpmn_activitylabel")
            protected String bpmnActivitylabel;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the bpmnActivityid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnActivityid() {
                return bpmnActivityid;
            }

            /**
             * Sets the value of the bpmnActivityid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnActivityid(String value) {
                this.bpmnActivityid = value;
            }

            /**
             * Gets the value of the competencyid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompetencyid() {
                return competencyid;
            }

            /**
             * Sets the value of the competencyid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompetencyid(String value) {
                this.competencyid = value;
            }

            /**
             * Gets the value of the bpmnActivitylabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnActivitylabel() {
                return bpmnActivitylabel;
            }

            /**
             * Sets the value of the bpmnActivitylabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnActivitylabel(String value) {
                this.bpmnActivitylabel = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LearningGoal" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LearningScenario">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="lsid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="KPIs" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "learningGoal"
    })
    public static class LearningGoals {

        @XmlElement(name = "LearningGoal")
        protected List<LearningPath.LearningGoals.LearningGoal> learningGoal;

        /**
         * Gets the value of the learningGoal property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the learningGoal property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLearningGoal().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LearningPath.LearningGoals.LearningGoal }
         * 
         * 
         */
        public List<LearningPath.LearningGoals.LearningGoal> getLearningGoal() {
            if (learningGoal == null) {
                learningGoal = new ArrayList<LearningPath.LearningGoals.LearningGoal>();
            }
            return this.learningGoal;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LearningScenario">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="lsid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="KPIs" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "learningScenario",
            "kpIs"
        })
        public static class LearningGoal {

            @XmlElement(name = "LearningScenario", required = true)
            protected LearningPath.LearningGoals.LearningGoal.LearningScenario learningScenario;
            @XmlElement(name = "KPIs", required = true)
            protected String kpIs;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the learningScenario property.
             * 
             * @return
             *     possible object is
             *     {@link LearningPath.LearningGoals.LearningGoal.LearningScenario }
             *     
             */
            public LearningPath.LearningGoals.LearningGoal.LearningScenario getLearningScenario() {
                return learningScenario;
            }

            /**
             * Sets the value of the learningScenario property.
             * 
             * @param value
             *     allowed object is
             *     {@link LearningPath.LearningGoals.LearningGoal.LearningScenario }
             *     
             */
            public void setLearningScenario(LearningPath.LearningGoals.LearningGoal.LearningScenario value) {
                this.learningScenario = value;
            }

            /**
             * Gets the value of the kpIs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKPIs() {
                return kpIs;
            }

            /**
             * Sets the value of the kpIs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKPIs(String value) {
                this.kpIs = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="lsid" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class LearningScenario {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "lsid")
                protected String lsid;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the lsid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLsid() {
                    return lsid;
                }

                /**
                 * Sets the value of the lsid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLsid(String value) {
                    this.lsid = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PreLearningPath" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="pre_lpid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "preLearningPath"
    })
    public static class Prerequesties {

        @XmlElement(name = "PreLearningPath")
        protected List<LearningPath.Prerequesties.PreLearningPath> preLearningPath;

        /**
         * Gets the value of the preLearningPath property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the preLearningPath property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPreLearningPath().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LearningPath.Prerequesties.PreLearningPath }
         * 
         * 
         */
        public List<LearningPath.Prerequesties.PreLearningPath> getPreLearningPath() {
            if (preLearningPath == null) {
                preLearningPath = new ArrayList<LearningPath.Prerequesties.PreLearningPath>();
            }
            return this.preLearningPath;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="pre_lpid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class PreLearningPath {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "pre_lpid")
            protected String preLpid;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the preLpid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPreLpid() {
                return preLpid;
            }

            /**
             * Sets the value of the preLpid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPreLpid(String value) {
                this.preLpid = value;
            }

        }

    }

}
