//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.24 at 11:44:36 AM CEST 
//


package it.cnr.isti.labsedc.bpmls.learningpathspec;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scenariocontexthint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Trace">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vertex" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TargetVertexes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vertex" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="activitycontexthint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InitialValuation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataObject" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_camundaid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_dolabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ValuationOracle" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ValuationFunction" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DataObject" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ExpectedValue">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="DoHint">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="bpmn_camundaid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="bpmn_dolabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bpmn_processlabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bpmn_processid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scenariocontexthint",
    "trace",
    "targetVertexes",
    "initialValuation",
    "valuationOracle"
})
@XmlRootElement(name = "LearningScenario")
public class LearningScenario {

    @XmlElement(required = true)
    protected String scenariocontexthint;
    @XmlElement(name = "Trace", required = true)
    protected LearningScenario.Trace trace;
    @XmlElement(name = "TargetVertexes", required = true)
    protected LearningScenario.TargetVertexes targetVertexes;
    @XmlElement(name = "InitialValuation", required = true)
    protected LearningScenario.InitialValuation initialValuation;
    @XmlElement(name = "ValuationOracle")
    protected LearningScenario.ValuationOracle valuationOracle;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "bpmn_processlabel")
    protected String bpmnProcesslabel;
    @XmlAttribute(name = "bpmn_processid")
    protected String bpmnProcessid;

    /**
     * Gets the value of the scenariocontexthint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenariocontexthint() {
        return scenariocontexthint;
    }

    /**
     * Sets the value of the scenariocontexthint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenariocontexthint(String value) {
        this.scenariocontexthint = value;
    }

    /**
     * Gets the value of the trace property.
     * 
     * @return
     *     possible object is
     *     {@link LearningScenario.Trace }
     *     
     */
    public LearningScenario.Trace getTrace() {
        return trace;
    }

    /**
     * Sets the value of the trace property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningScenario.Trace }
     *     
     */
    public void setTrace(LearningScenario.Trace value) {
        this.trace = value;
    }

    /**
     * Gets the value of the targetVertexes property.
     * 
     * @return
     *     possible object is
     *     {@link LearningScenario.TargetVertexes }
     *     
     */
    public LearningScenario.TargetVertexes getTargetVertexes() {
        return targetVertexes;
    }

    /**
     * Sets the value of the targetVertexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningScenario.TargetVertexes }
     *     
     */
    public void setTargetVertexes(LearningScenario.TargetVertexes value) {
        this.targetVertexes = value;
    }

    /**
     * Gets the value of the initialValuation property.
     * 
     * @return
     *     possible object is
     *     {@link LearningScenario.InitialValuation }
     *     
     */
    public LearningScenario.InitialValuation getInitialValuation() {
        return initialValuation;
    }

    /**
     * Sets the value of the initialValuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningScenario.InitialValuation }
     *     
     */
    public void setInitialValuation(LearningScenario.InitialValuation value) {
        this.initialValuation = value;
    }

    /**
     * Gets the value of the valuationOracle property.
     * 
     * @return
     *     possible object is
     *     {@link LearningScenario.ValuationOracle }
     *     
     */
    public LearningScenario.ValuationOracle getValuationOracle() {
        return valuationOracle;
    }

    /**
     * Sets the value of the valuationOracle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningScenario.ValuationOracle }
     *     
     */
    public void setValuationOracle(LearningScenario.ValuationOracle value) {
        this.valuationOracle = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bpmnProcesslabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBpmnProcesslabel() {
        return bpmnProcesslabel;
    }

    /**
     * Sets the value of the bpmnProcesslabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBpmnProcesslabel(String value) {
        this.bpmnProcesslabel = value;
    }

    /**
     * Gets the value of the bpmnProcessid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBpmnProcessid() {
        return bpmnProcessid;
    }

    /**
     * Sets the value of the bpmnProcessid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBpmnProcessid(String value) {
        this.bpmnProcessid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataObject" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_camundaid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_dolabel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataObject"
    })
    public static class InitialValuation {

        @XmlElement(name = "DataObject")
        protected List<LearningScenario.InitialValuation.DataObject> dataObject;

        /**
         * Gets the value of the dataObject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataObject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LearningScenario.InitialValuation.DataObject }
         * 
         * 
         */
        public List<LearningScenario.InitialValuation.DataObject> getDataObject() {
            if (dataObject == null) {
                dataObject = new ArrayList<LearningScenario.InitialValuation.DataObject>();
            }
            return this.dataObject;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_camundaid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_dolabel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DataObject {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "bpmn_camundaid")
            protected String bpmnCamundaid;
            @XmlAttribute(name = "bpmn_dolabel")
            protected String bpmnDolabel;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the bpmnCamundaid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnCamundaid() {
                return bpmnCamundaid;
            }

            /**
             * Sets the value of the bpmnCamundaid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnCamundaid(String value) {
                this.bpmnCamundaid = value;
            }

            /**
             * Gets the value of the bpmnDolabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnDolabel() {
                return bpmnDolabel;
            }

            /**
             * Sets the value of the bpmnDolabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnDolabel(String value) {
                this.bpmnDolabel = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vertex" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="activitycontexthint" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vertex"
    })
    public static class TargetVertexes {

        protected List<LearningScenario.TargetVertexes.Vertex> vertex;

        /**
         * Gets the value of the vertex property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vertex property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVertex().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LearningScenario.TargetVertexes.Vertex }
         * 
         * 
         */
        public List<LearningScenario.TargetVertexes.Vertex> getVertex() {
            if (vertex == null) {
                vertex = new ArrayList<LearningScenario.TargetVertexes.Vertex>();
            }
            return this.vertex;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="activitycontexthint" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "activitycontexthint"
        })
        public static class Vertex {

            @XmlElement(required = true)
            protected String activitycontexthint;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "bpmn_activityid")
            protected String bpmnActivityid;
            @XmlAttribute(name = "bpmn_activitylabel")
            protected String bpmnActivitylabel;

            /**
             * Gets the value of the activitycontexthint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivitycontexthint() {
                return activitycontexthint;
            }

            /**
             * Sets the value of the activitycontexthint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivitycontexthint(String value) {
                this.activitycontexthint = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the bpmnActivityid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnActivityid() {
                return bpmnActivityid;
            }

            /**
             * Sets the value of the bpmnActivityid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnActivityid(String value) {
                this.bpmnActivityid = value;
            }

            /**
             * Gets the value of the bpmnActivitylabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnActivitylabel() {
                return bpmnActivitylabel;
            }

            /**
             * Sets the value of the bpmnActivitylabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnActivitylabel(String value) {
                this.bpmnActivitylabel = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vertex" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vertex"
    })
    public static class Trace {

        protected List<LearningScenario.Trace.Vertex> vertex;

        /**
         * Gets the value of the vertex property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vertex property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVertex().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LearningScenario.Trace.Vertex }
         * 
         * 
         */
        public List<LearningScenario.Trace.Vertex> getVertex() {
            if (vertex == null) {
                vertex = new ArrayList<LearningScenario.Trace.Vertex>();
            }
            return this.vertex;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Vertex {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "bpmn_activityid")
            protected String bpmnActivityid;
            @XmlAttribute(name = "bpmn_activitylabel")
            protected String bpmnActivitylabel;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the bpmnActivityid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnActivityid() {
                return bpmnActivityid;
            }

            /**
             * Sets the value of the bpmnActivityid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnActivityid(String value) {
                this.bpmnActivityid = value;
            }

            /**
             * Gets the value of the bpmnActivitylabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnActivitylabel() {
                return bpmnActivitylabel;
            }

            /**
             * Sets the value of the bpmnActivitylabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnActivitylabel(String value) {
                this.bpmnActivitylabel = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ValuationFunction" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DataObject" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ExpectedValue">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="DoHint">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="bpmn_camundaid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="bpmn_dolabel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "valuationFunction"
    })
    public static class ValuationOracle {

        @XmlElement(name = "ValuationFunction", required = true)
        protected List<LearningScenario.ValuationOracle.ValuationFunction> valuationFunction;

        /**
         * Gets the value of the valuationFunction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the valuationFunction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValuationFunction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LearningScenario.ValuationOracle.ValuationFunction }
         * 
         * 
         */
        public List<LearningScenario.ValuationOracle.ValuationFunction> getValuationFunction() {
            if (valuationFunction == null) {
                valuationFunction = new ArrayList<LearningScenario.ValuationOracle.ValuationFunction>();
            }
            return this.valuationFunction;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DataObject" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ExpectedValue">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="DoHint">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="bpmn_camundaid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="bpmn_dolabel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_activityid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmn_activitylabel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dataObject"
        })
        public static class ValuationFunction {

            @XmlElement(name = "DataObject", required = true)
            protected List<LearningScenario.ValuationOracle.ValuationFunction.DataObject> dataObject;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "bpmn_activityid")
            protected String bpmnActivityid;
            @XmlAttribute(name = "bpmn_activitylabel")
            protected String bpmnActivitylabel;

            /**
             * Gets the value of the dataObject property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dataObject property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDataObject().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link LearningScenario.ValuationOracle.ValuationFunction.DataObject }
             * 
             * 
             */
            public List<LearningScenario.ValuationOracle.ValuationFunction.DataObject> getDataObject() {
                if (dataObject == null) {
                    dataObject = new ArrayList<LearningScenario.ValuationOracle.ValuationFunction.DataObject>();
                }
                return this.dataObject;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the bpmnActivityid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnActivityid() {
                return bpmnActivityid;
            }

            /**
             * Sets the value of the bpmnActivityid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnActivityid(String value) {
                this.bpmnActivityid = value;
            }

            /**
             * Gets the value of the bpmnActivitylabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnActivitylabel() {
                return bpmnActivitylabel;
            }

            /**
             * Sets the value of the bpmnActivitylabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnActivitylabel(String value) {
                this.bpmnActivitylabel = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ExpectedValue">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="DoHint">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="bpmn_camundaid" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="bpmn_dolabel" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "expectedValue",
                "doHint"
            })
            public static class DataObject {

                @XmlElement(name = "ExpectedValue", required = true)
                protected LearningScenario.ValuationOracle.ValuationFunction.DataObject.ExpectedValue expectedValue;
                @XmlElement(name = "DoHint", required = true)
                protected LearningScenario.ValuationOracle.ValuationFunction.DataObject.DoHint doHint;
                @XmlAttribute(name = "id")
                protected String id;
                @XmlAttribute(name = "bpmn_camundaid")
                protected String bpmnCamundaid;
                @XmlAttribute(name = "bpmn_dolabel")
                protected String bpmnDolabel;

                /**
                 * Gets the value of the expectedValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LearningScenario.ValuationOracle.ValuationFunction.DataObject.ExpectedValue }
                 *     
                 */
                public LearningScenario.ValuationOracle.ValuationFunction.DataObject.ExpectedValue getExpectedValue() {
                    return expectedValue;
                }

                /**
                 * Sets the value of the expectedValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LearningScenario.ValuationOracle.ValuationFunction.DataObject.ExpectedValue }
                 *     
                 */
                public void setExpectedValue(LearningScenario.ValuationOracle.ValuationFunction.DataObject.ExpectedValue value) {
                    this.expectedValue = value;
                }

                /**
                 * Gets the value of the doHint property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LearningScenario.ValuationOracle.ValuationFunction.DataObject.DoHint }
                 *     
                 */
                public LearningScenario.ValuationOracle.ValuationFunction.DataObject.DoHint getDoHint() {
                    return doHint;
                }

                /**
                 * Sets the value of the doHint property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LearningScenario.ValuationOracle.ValuationFunction.DataObject.DoHint }
                 *     
                 */
                public void setDoHint(LearningScenario.ValuationOracle.ValuationFunction.DataObject.DoHint value) {
                    this.doHint = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the bpmnCamundaid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBpmnCamundaid() {
                    return bpmnCamundaid;
                }

                /**
                 * Sets the value of the bpmnCamundaid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBpmnCamundaid(String value) {
                    this.bpmnCamundaid = value;
                }

                /**
                 * Gets the value of the bpmnDolabel property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBpmnDolabel() {
                    return bpmnDolabel;
                }

                /**
                 * Sets the value of the bpmnDolabel property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBpmnDolabel(String value) {
                    this.bpmnDolabel = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class DoHint {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "id")
                    protected String id;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setId(String value) {
                        this.id = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class ExpectedValue {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "id")
                    protected String id;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setId(String value) {
                        this.id = value;
                    }

                }

            }

        }

    }

}
