//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 03:56:47 PM CEST 
//


package it.cnr.isti.labsedc.bpmls.learningpathspec;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.cnr.isti.labsedc.bpmls.learningpathspec package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.cnr.isti.labsedc.bpmls.learningpathspec
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LearningScenario }
     * 
     */
    public LearningScenario createLearningScenario() {
        return new LearningScenario();
    }

    /**
     * Create an instance of {@link LearningScenario.ValuationOracle }
     * 
     */
    public LearningScenario.ValuationOracle createLearningScenarioValuationOracle() {
        return new LearningScenario.ValuationOracle();
    }

    /**
     * Create an instance of {@link LearningScenario.ValuationOracle.ValuationFunction }
     * 
     */
    public LearningScenario.ValuationOracle.ValuationFunction createLearningScenarioValuationOracleValuationFunction() {
        return new LearningScenario.ValuationOracle.ValuationFunction();
    }

    /**
     * Create an instance of {@link LearningScenario.ValuationOracle.ValuationFunction.DataObject }
     * 
     */
    public LearningScenario.ValuationOracle.ValuationFunction.DataObject createLearningScenarioValuationOracleValuationFunctionDataObject() {
        return new LearningScenario.ValuationOracle.ValuationFunction.DataObject();
    }

    /**
     * Create an instance of {@link LearningScenario.InitialValuation }
     * 
     */
    public LearningScenario.InitialValuation createLearningScenarioInitialValuation() {
        return new LearningScenario.InitialValuation();
    }

    /**
     * Create an instance of {@link LearningScenario.TargetVertexes }
     * 
     */
    public LearningScenario.TargetVertexes createLearningScenarioTargetVertexes() {
        return new LearningScenario.TargetVertexes();
    }

    /**
     * Create an instance of {@link LearningScenario.Trace }
     * 
     */
    public LearningScenario.Trace createLearningScenarioTrace() {
        return new LearningScenario.Trace();
    }

    /**
     * Create an instance of {@link LearningScenario.ValuationOracle.ValuationFunction.DataObject.ExpectedValue }
     * 
     */
    public LearningScenario.ValuationOracle.ValuationFunction.DataObject.ExpectedValue createLearningScenarioValuationOracleValuationFunctionDataObjectExpectedValue() {
        return new LearningScenario.ValuationOracle.ValuationFunction.DataObject.ExpectedValue();
    }

    /**
     * Create an instance of {@link LearningScenario.ValuationOracle.ValuationFunction.DataObject.DoHint }
     * 
     */
    public LearningScenario.ValuationOracle.ValuationFunction.DataObject.DoHint createLearningScenarioValuationOracleValuationFunctionDataObjectDoHint() {
        return new LearningScenario.ValuationOracle.ValuationFunction.DataObject.DoHint();
    }

    /**
     * Create an instance of {@link LearningScenario.InitialValuation.DataObject }
     * 
     */
    public LearningScenario.InitialValuation.DataObject createLearningScenarioInitialValuationDataObject() {
        return new LearningScenario.InitialValuation.DataObject();
    }

    /**
     * Create an instance of {@link LearningScenario.TargetVertexes.Vertex }
     * 
     */
    public LearningScenario.TargetVertexes.Vertex createLearningScenarioTargetVertexesVertex() {
        return new LearningScenario.TargetVertexes.Vertex();
    }

    /**
     * Create an instance of {@link LearningScenario.Trace.Vertex }
     * 
     */
    public LearningScenario.Trace.Vertex createLearningScenarioTraceVertex() {
        return new LearningScenario.Trace.Vertex();
    }

}
