//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 05:19:41 PM CEST 
//


package it.cnr.isti.labsedc.bpmls.learningpathspec;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.cnr.isti.labsedc.bpmls.learningpathspec package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.cnr.isti.labsedc.bpmls.learningpathspec
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LearningPath }
     * 
     */
    public LearningPath createLearningPath() {
        return new LearningPath();
    }

    /**
     * Create an instance of {@link LearningPath.LearningGoals }
     * 
     */
    public LearningPath.LearningGoals createLearningPathLearningGoals() {
        return new LearningPath.LearningGoals();
    }

    /**
     * Create an instance of {@link LearningPath.LearningGoals.LearningGoal }
     * 
     */
    public LearningPath.LearningGoals.LearningGoal createLearningPathLearningGoalsLearningGoal() {
        return new LearningPath.LearningGoals.LearningGoal();
    }

    /**
     * Create an instance of {@link LearningPath.LearningGoals.LearningGoal.LearningScenarios }
     * 
     */
    public LearningPath.LearningGoals.LearningGoal.LearningScenarios createLearningPathLearningGoalsLearningGoalLearningScenarios() {
        return new LearningPath.LearningGoals.LearningGoal.LearningScenarios();
    }

    /**
     * Create an instance of {@link LearningPath.LearningActivities }
     * 
     */
    public LearningPath.LearningActivities createLearningPathLearningActivities() {
        return new LearningPath.LearningActivities();
    }

    /**
     * Create an instance of {@link LearningPath.Competencies }
     * 
     */
    public LearningPath.Competencies createLearningPathCompetencies() {
        return new LearningPath.Competencies();
    }

    /**
     * Create an instance of {@link LearningPath.Prerequesties }
     * 
     */
    public LearningPath.Prerequesties createLearningPathPrerequesties() {
        return new LearningPath.Prerequesties();
    }

    /**
     * Create an instance of {@link LearningPath.LearningGoals.LearningGoal.LearningScenarios.LearningScenario }
     * 
     */
    public LearningPath.LearningGoals.LearningGoal.LearningScenarios.LearningScenario createLearningPathLearningGoalsLearningGoalLearningScenariosLearningScenario() {
        return new LearningPath.LearningGoals.LearningGoal.LearningScenarios.LearningScenario();
    }

    /**
     * Create an instance of {@link LearningPath.LearningActivities.LearningActivity }
     * 
     */
    public LearningPath.LearningActivities.LearningActivity createLearningPathLearningActivitiesLearningActivity() {
        return new LearningPath.LearningActivities.LearningActivity();
    }

    /**
     * Create an instance of {@link LearningPath.Competencies.Competency }
     * 
     */
    public LearningPath.Competencies.Competency createLearningPathCompetenciesCompetency() {
        return new LearningPath.Competencies.Competency();
    }

    /**
     * Create an instance of {@link LearningPath.Prerequesties.PreLearningPath }
     * 
     */
    public LearningPath.Prerequesties.PreLearningPath createLearningPathPrerequestiesPreLearningPath() {
        return new LearningPath.Prerequesties.PreLearningPath();
    }

}
