//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.25 at 04:31:18 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.isti.cnr.it/research/unit.php?unit=SEDC", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.cnr.isti.labsedc.bpmls.senarios;
